### ISSUE TITLE
first gesture is slow to respond

### ISSUE THREAD

**Issue by brunotorrao** [Hikari9/comfortable-swipe#30] opened 2018-08-02 14:57 UTC
The first gesture after some time is always slow. I dont know if there is something to do with the OS or is something that can be improved.
I'm using Ubuntu 18

**Comment by Hikari9** [comment] 2018-09-26 07:54
@brunotorrao thanks for this info. I think this might have to do with bottlenecked startup process. Did you run with autostart on?
```
comfortable-swipe autostart
```

Also, if you can, please reply the output of:
```
lsb_release -a
```

**Comment by robertoferreirajrr** [comment] 2019-02-02 10:11
Hi @Hikari9 , same here... 
autostart is on

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic

First gesture time is always slow, like a 2 seconds delay to gesture dispare the event... after that all works fine

**Comment by Hikari9** [comment] 2019-02-06 15:52
Thanks for raising this.

I'm using 18.04 as well, but cannot replicate it. I'm thinking it might be some buffering issue from C++ input streams. Or maybe libinput may have a lot of buffered output on startup. Most likely it's the latter... 

Looking into solutions right now. Will keep you updated :)

**Comment by robertoferreirajrr** [comment] 2019-02-07 10:42
Hi @Hikari9 , thanks for your reply. I'll wait for a new version in hope that this solves my problem =) 

Best regards

**Comment by Hikari9** [comment] 2019-02-12 09:41
@robertoferreirajrr @brunotorrao I believe I have found the issue to this delay.

The delay is caused by the underlying library `xdotool`. Every key gesture seem to have around 1.5-2 second delay for every call to xdotool. Similar issues are found in similar libraries (see [libinput-gestures](https://github.com/bulletmark/libinput-gestures/issues/151) and [fusuma](https://github.com/iberianpig/fusuma/issues/113)). This issue hasn't been resolved in their implementations... **Fortunately**, since comfortable-swipe uses xdotool natively with C++, I think I have a solution to this problem :smile:

Preloading xdotool on construction will do the trick. Please wait for the next PR. Thanks!

**Comment by Hikari9** [comment] 2019-02-12 09:52
The library has been updated :) Please perform installation instructions in the README again. Thanks!

**Comment by robertoferreirajrr** [comment] 2019-02-12 16:57
Hi @Hikari9 . Thanks for all =)... Very better now! =)

**Closed as completed** 2019-02-12 23:46 UTC
