### ISSUE TITLE
Default install not working on Kubuntu Bionic LTS

### ISSUE THREAD

**Issue by sylvansab** [Hikari9/comfortable-swipe#48] opened 2019-02-08 22:14 UTC
I am very enticed by this project. Unfortunately it seems not to work on my Kubuntu 18.04, despite running the install exactly as outlined, only a couple hours ago.

I also ran the tests, which are all PASSED : https://pastebin.com/XgevMQDk

I'm not sure what's wrong. I use all the same keyboard shortcuts as set by default, and I have tried various "threshold" values, to no avail...

How can I help you make this work under my OS ?

**Comment by sylvansab** [comment] 2019-02-08 23:07
After some workaround with xdotool, and reading the libinput doc, it seems it has to do with the detection of my "intended" gestures... libinput-debug-events doesn't seem to show any GESTURE_SWIPE_XXX of any kind, but rather POINTER_AXIS which I have been able to provoke. Maybe something to do with [my touchpad only able to recognize so many fingers](https://wayland.freedesktop.org/libinput/doc/latest/touchpads.html#touch-capabilities) ?

**Comment by Hikari9** [comment] 2019-02-09 11:57
@sylvainsab unfortunately, the tests are not exhaustive... they only make sure the regex will work with what `libinput debug-gestures` should output (ie. GESTURE_SWIPE_XXX).

Does your touchpad support multiple gestures? What driver are you using? Please print output of
```
xinput list | grep touchpad -i
```

and 
```
lsmod | grep hid
```

**Comment by sylvansab** [comment] 2019-02-09 13:54
```
~$ xinput list
⎡ Virtual core pointer                          id=2    [master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer                id=4    [slave  pointer  (2)]
⎜   ↳ SynPS/2 Synaptics TouchPad                id=12   [slave  pointer  (2)]
...
~$ lsmod | grep hid
mac_hid                16384  0
```

**Comment by Hikari9** [comment] 2019-02-10 09:09
You're using a Mac? You might need to install additional drivers to make it work. Try checking [this](https://github.com/Dunedan/mbp-2016-linux#keyboard--touchpad)

**Comment by sylvansab** [comment] 2019-02-10 10:05
A Mac ? No, but it's interesting you raise the question. What would make you think that ? I actually use a laptop assembled by a company that used to sell computers with no OS or with Linux. Alusa - now defunct.

I'm going to try the patch.

**Comment by Hikari9** [comment] 2019-02-11 04:42
Sorry, i was misled by your output that said mac_hid. I used to see that usually on MacBook touchpads.

In terms of your other comments, as I would point out, POINTER_AXIS is an indicator of two finger gesture (ie. Scrolling), so if you can't see GESTURE_SWIPE_XXX, then your touchpad either isn't updated or doesn't support gestures with at least 3 fingers.

**Comment by Hikari9** [comment] 2019-02-11 04:45
Can you test other multi-click gestures, such as 3 finger middle click? Since you're using synclient, you can run
```
synclient TapButton3=2
```

Try three finger tapping any link to verify it opens new tabs

**Comment by Hikari9** [comment] 2019-02-11 05:44
You can also check out the answers from issue #23 and see if any of them work :)

_Here's a summary of some of the solutions_:

1.  Do check if you may have **not yet enabled workspaces** in your Kubuntu.
Check out this forum on [how to enable multiple desktops in KDE](https://www.google.com/search?q=multiple+desktops+kubuntu&oq=multiple+desktops+kubuntu&aqs=chrome.0.0j69i57.3418j1j4&sourceid=chrome&ie=UTF-8) 

2. Can you print the result of
```
libinput list-devices | grep Touchpad -i -A 17
```

Output should look something like this:
```
Device:           Asus TouchPad
Kernel:           /dev/input/event15
Group:            7
Seat:             seat0, default
Size:             70x50mm
Capabilities:     pointer gesture
Tap-to-click:     disabled
Tap-and-drag:     enabled
Tap drag lock:    disabled
Left-handed:      disabled
Nat.scrolling:    disabled
Middle emulation: disabled
Calibration:      n/a
Scroll methods:   *two-finger edge 
Click methods:    *button-areas clickfinger 
Disable-w-typing: enabled
Accel profiles:   none
Rotation:         n/a
```

After this, please run
```
libinput debug-events --device /dev/input/event#
```

Replace `#` with the kernel from the previous output. In my case, it's `/dev/input/event15`.

It should show something like this:

```
$ libinput debug-events --device /dev/input/event15

-event15  DEVICE_ADDED     Asus TouchPad                     seat0 default group1  cap:pg  size 70x50mm tap(dl off) left scroll-nat scroll-2fg-edge click-buttonareas-clickfinger dwt-on
 event15  GESTURE_SWIPE_BEGIN  +2.91s	3
 event15  GESTURE_SWIPE_UPDATE  +2.91s	3 -6.56/ 2.92 (-25.26/11.25 unaccelerated)
 event15  GESTURE_SWIPE_UPDATE  +2.91s	3 -9.71/ 5.41 (-26.25/14.62 unaccelerated)
 event15  GESTURE_SWIPE_END  +2.94s	3
 event15  GESTURE_SWIPE_BEGIN  +3.42s	3
 event15  GESTURE_SWIPE_UPDATE  +3.42s	3 12.62/-2.08 (34.12/-5.62 unaccelerated)
 event15  GESTURE_SWIPE_UPDATE  +3.42s	3 13.60/-1.53 (36.75/-4.12 unaccelerated)
 event15  GESTURE_SWIPE_UPDATE  +3.43s	3 13.11/-1.80 (35.43/-4.87 unaccelerated)
 event15  GESTURE_SWIPE_UPDATE  +3.44s	3 12.50/-1.66 (33.79/-4.50 unaccelerated)
 event15  GESTURE_SWIPE_UPDATE  +3.44s	3 11.29/-1.53 (30.51/-4.12 unaccelerated)
 event15  GESTURE_SWIPE_UPDATE  +3.45s	3 10.32/-1.11 (27.89/-3.00 unaccelerated)
 event15  GESTURE_SWIPE_UPDATE  +3.46s	3  8.86/-0.69 (23.95/-1.87 unaccelerated)
 event15  GESTURE_SWIPE_END  +3.50s	3
```

If you see `GESTURE_SWIPE_XXX` during a finger swipe, then it should work.

3. Otherwise, the problem may lie in your keyboard shortcuts in your configurations. Type
```
nano /usr/local/share/comfortable-swipe/comfortable-swipe.conf
```
to edit your configurations. Make sure you use those *supported by xdotool* (see `man xdotool`)

**Comment by sylvansab** [comment] 2019-02-11 08:29
OK, I read the thread and tried what you recommend : https://github.com/Hikari9/comfortable-swipe-ubuntu/issues/23#issuecomment-355872605

(for some reason this won't be displayed correctly...)
`~$ libinput list-devices | grep Touchpad -i -A 17
Device:           SynPS/2 Synaptics TouchPad
Kernel:           /dev/input/event6
Group:            9
Seat:             seat0, default
Size:             64x32mm
Capabilities:     pointer 
Tap-to-click:     disabled
Tap-and-drag:     enabled
Tap drag lock:    disabled
Left-handed:      disabled
Nat.scrolling:    disabled
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   *two-finger edge 
Click methods:    none
Disable-w-typing: enabled
Accel profiles:   none
Rotation:         n/a`

The configuration file is also good. I think the problem might come from my touchpad which would not support 3-fingers swipes, indeed there is no `GESTURE_SWIPE_XXX` displayed when I do the swipe gesture, only `POINTER_AXIS`.

**Comment by Hikari9** [comment] 2019-02-12 09:32
Ok, closing this issue since the problem is hardware-related.

**Closed as completed by Hikari9** 2019-02-12 09:32 UTC
